services:
  db:
    image: postgres:18-alpine
    container_name: delta-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: delta-drizzle-gateway
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/postgres
      STORE_PATH: /app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "4983:4983"
    volumes:
      - drizzle_gateway_data:/app

volumes:
  postgres_data:
  drizzle_gateway_data:
